#!/system/bin/sh

echo "1" > /sys/devices/platform/kp_leds-gpio/leds/BLUE_LED/brightness

#CPU
MIN_FREQ="300000"
MAX_FREQ="1000000"
echo $MIN_FREQ > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
echo $MAX_FREQ > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq

#Powersave
#GOV="conservative"
#echo $GOV > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
#echo "75" > /sys/devices/system/cpu/cpufreq/conservative/up_threshold
#echo "5" > /sys/devices/system/cpu/cpufreq/conservative/sampling_down_factor
#echo "30" > /sys/devices/system/cpu/cpufreq/conservative/down_threshold
#echo "20" > /sys/devices/system/cpu/cpufreq/conservative/freq_step
#echo "1" > /sys/devices/system/cpu/cpufreq/conservative/ignore_nice_load

#Performance
echo "40000" > /sys/devices/system/cpu/cpufreq/pegasusq/sampling_rate;
echo "80" > /sys/devices/system/cpu/cpufreq/pegasusq/up_threshold;
echo "2" > /sys/devices/system/cpu/cpufreq/pegasusq/sampling_down_factor;
echo "5" > /sys/devices/system/cpu/cpufreq/pegasusq/down_differential;
echo "20" > /sys/devices/system/cpu/cpufreq/pegasusq/freq_step;
echo "15" > /sys/devices/system/cpu/cpufreq/pegasusq/cpu_up_rate
echo "15" > /sys/devices/system/cpu/cpufreq/pegasusq/cpu_down_rate
echo "0" > /sys/devices/system/cpu/cpufreq/pegasusq/max_cpu_lock;
echo "0" > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_lock;
echo "1" > /sys/devices/system/cpu/cpufreq/pegasusq/ignore_nice_load;
echo 500000 > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_freq_1_1;
echo 600000 > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_freq_2_0;
echo 700000 > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_freq_2_1;
echo 800000 > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_freq_3_0;
echo 900000 > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_freq_3_1;
echo 800000 > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_freq_4_0;
echo 200 > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_rq_1_1;
echo 150 > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_rq_2_0;
echo 250 > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_rq_2_1;
echo 300 > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_rq_3_0;
echo 400 > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_rq_3_1;
echo 400 > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_rq_4_0;

#GPU
echo 160 > /sys/module/mali/parameters/step0_clk
echo 85 > /sys/module/mali/parameters/step0_up
echo 160 > /sys/module/mali/parameters/step1_clk
echo 89 > /sys/module/mali/parameters/step1_down
echo 90 > /sys/module/mali/parameters/step1_up
echo 160 > /sys/module/mali/parameters/step2_clk
echo 94 > /sys/module/mali/parameters/step2_down
echo 95 > /sys/module/mali/parameters/step2_up
echo 160 > /sys/module/mali/parameters/step3_clk
echo 99 > /sys/module/mali/parameters/step3_down
echo 25 > /sys/module/mali/parameters/mali_l2_max_reads 
echo 5000 > /sys/ module/mali/parameters/mali_max_job_runtime

#IO
Sched="deadline"
echo $Sched > /sys/block/mmcblk0/queue/scheduler

#VM
echo "60" > /proc/sys/vm/swappiness

echo "10" > /proc/sys/vm/vfs_cache_pressure

echo "500" > /proc/sys/vm/dirty_expire_centisecs

echo "1000" > /proc/sys/vm/dirty_writeback_centisecs

echo "90" > /proc/sys/vm/dirty_ratio

echo "5" > /proc/sys/vm/dirty_background_ratio

echo "0" > /proc/sys/vm/oom_kill_allocating_task

busybox sleep 10s

#Kill Media server process
killall -9 android.process.media
killall -9 mediaserver

# Remount ext4 partitions with optimizations - noatime nodiratime
busybox mount -o remount,noatime,noauto_da_alloc,nodiratime,barrier=0,nobh /system
busybox mount -o remount,noatime,noauto_da_alloc,nosuid,nodev,nodiratime,barrier=0,nobh /data
busybox mount -o remount,noatime,noauto_da_alloc,nosuid,nodev,nodiratime,barrier=0,nobh /cache

# Removes Journalism
tune2fs -o journal_data_writeback /block/path/to/system
tune2fs -O ^has_journal /block/path/to/system
tune2fs -o journal_data_writeback /block/path/to/cache
tune2fs -O ^has_journal /block/path/to/cache
tune2fs -o journal_data_writeback /block/path/to/data
tune2fs -O ^has_journal /block/path/to/data

# Turn off debugging for certain modules
  echo "0" > /sys/module/wakelock/parameters/debug_mask
  echo "0" > /sys/module/userwakelock/parameters/debug_mask
  echo "0" > /sys/module/earlysuspend/parameters/debug_mask
  echo "0" > /sys/module/alarm/parameters/debug_mask
  echo "0" > /sys/module/alarm_dev/parameters/debug_mask
  echo "0" > /sys/module/binder/parameters/debug_mask

# MicroSD Card Speed Tweak
READ_AHEAD_KB="2049"

if [ -e /sys/devices/virtual/bdi/0:18/read_ahead_kb ]; then
    echo $READ_AHEAD_KB > /sys/devices/virtual/bdi/0:18/read_ahead_kb
fi

if [ -e /sys/devices/virtual/bdi/179:0/read_ahead_kb ]; then
    echo $READ_AHEAD_KB > /sys/devices/virtual/bdi/179:0/read_ahead_kb
fi

if [ -e /sys/devices/virtual/bdi/7:0/read_ahead_kb ]; then
    echo $READ_AHEAD_KB > /sys/devices/virtual/bdi/7:0/read_ahead_kb
fi

if [ -e /sys/devices/virtual/bdi/7:1/read_ahead_kb ]; then
    echo $READ_AHEAD_KB > /sys/devices/virtual/bdi/7:1/read_ahead_kb
fi

if [ -e /sys/devices/virtual/bdi/7:2/read_ahead_kb ]; then
    echo $READ_AHEAD_KB > /sys/devices/virtual/bdi/7:2/read_ahead_kb
fi

if [ -e /sys/devices/virtual/bdi/7:3/read_ahead_kb ]; then
    echo $READ_AHEAD_KB > /sys/devices/virtual/bdi/7:3/read_ahead_kb
fi

if [ -e /sys/devices/virtual/bdi/7:4/read_ahead_kb ]; then
    echo $READ_AHEAD_KB > /sys/devices/virtual/bdi/7:4/read_ahead_kb
fi

if [ -e /sys/devices/virtual/bdi/7:5/read_ahead_kb ]; then
    echo $READ_AHEAD_KB > /sys/devices/virtual/bdi/7:5/read_ahead_kb
fi

if [ -e /sys/devices/virtual/bdi/7:6/read_ahead_kb ]; then
    echo $READ_AHEAD_KB > /sys/devices/virtual/bdi/7:6/read_ahead_kb
fi

if [ -e /sys/devices/virtual/bdi/7:7/read_ahead_kb ]; then
    echo $READ_AHEAD_KB > /sys/devices/virtual/bdi/7:7/read_ahead_kb
fi

if [ -e /sys/devices/virtual/bdi/default/read_ahead_kb ]; then
    echo $READ_AHEAD_KB > /sys/devices/virtual/bdi/default/read_ahead_kb
fi


# Clear Junk Caches And Junk Data
busybox find /data/data -type d -iname "*cache*" -exec busybox rm -f {}/* ';' -exec echo "Cleared {}" ';'
rm -f /data/local/*.apk
rm -f /data/local/tmp/*.apk
rm -f /data/*.log
rm -f /data/log/*.log
rm -f /cache/*.*
rm -f /cache/recovery/*.*
rm -f /data/system/dropbox/*.txt
rm -f /data/backup/pending/*.tmp
rm -f /data/tombstones/*.*

sleep 1
echo "0" > /sys/devices/platform/kp_leds-gpio/leds/BLUE_LED/brightness

